### ISSUE TITLE
Connector does not work on Micro Integrator / Integration studio

### ISSUE THREAD

**Issue by slcoleg** [wso2-extensions/esb-connector-amazons3#58]
**Description:**
Tried to execute sample from official site: https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/amazons3-connector/amazons3-connector-example/

Connector version 2.0.2

**Suggested Labels:**
AWS S3, WSO2mi

**Suggested Assignees:**

**Affected Product Version:**
2.0.3

**OS, DB, other environment details and versions:**    
* Windows 10, Integration Studio
* Ubuntu, Integration Studio

**Steps to reproduce:**
1. Load sample to IS from https://ei.docs.wso2.com/en/latest/micro-integrator/assets/attach/connectors/s3-connector.zip
2. Modify AWS S3 connection settings 
3. Use 'Export project artifacts and run" to execute under local MI
4. Try to get object from S3

What I see immediately after starting MI:
```
[2021-11-16 11:58:12,194]  INFO {EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
[2021-11-16 11:58:20,342]  INFO {LibraryArtifactDeployer} - Synapse Library named '{org.wso2.carbon.connector}amazons3' has been deployed from file : D:\Proj.Pivotree\IntegrationStudio\runtime\microesb\tmp\carbonapps\-1234\1637081899777TestCompositeApplication_1.0.0.car\amazons3-connector_2.0.2\amazons3-connector-2.0.2.zip
[2021-11-16 11:58:20,344]  INFO {SynapseImportFactory} - Successfully created Synapse Import: amazons3
[2021-11-16 11:58:20,385] **ERROR {ClassMediatorFactory} - Error in instantiating class : org.wso2.carbon.connector.amazons3.operations.BucketOperations java.lang.NoClassDefFoundError: software/amazon/awssdk/services/s3/model/BucketAlreadyExistsException**
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.newInstance(Class.java:412)
```
The same output when I changed connector to version 2.0.3

**Related Issues:**

**Comment by slcoleg** [comment]
Please mark the issue as resolved. I found I need to copy project related jars to the lib folder (at the end of the page): https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/amazons3-connector/amazons3-connector-config/

BTW: this list looks a little bit outdated as well as your readme.md file.

Thanks anyway.
